### ISSUE TITLE
New photos for coaches on homepage

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#1]
OS - OSX 10.11.5
Browser - Chrome

issue: photos of coaches are low resolution. Need better photos.

<img width="1123" alt="2016-06-28 18 06 55" src="https://cloud.githubusercontent.com/assets/20033472/16437366/2d58bd0a-3d5b-11e6-8e50-ad7c7e899085.png">

**Comment by windupmicheal** [comment]
comment on this issue

**Comment by prakharbhatia** [comment]
Please provide the photos.

**Comment by windupmicheal** [comment]
I'm working on collecting photos from coaches. Creating basecamp assignment for it

**Comment by highwayjourney** [comment]
replaced photos.

**Comment by windupmicheal** [comment]
Let's get Matt's head centered. Otherwise this looks good to me.

<img width="328" alt="2016-09-04 13 04 10" src="https://cloud.githubusercontent.com/assets/20033472/18233579/1d929e98-72a0-11e6-98c2-962286f6b923.png">

**Comment by highwayjourney** [comment]
changed photo.

**Comment by windupmicheal** [comment]
Verified. Closing bug. Can push to live site.
