### ISSUE TITLE
7-Step Guide popup needs to be implemented as designed.

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#10]
Here is the 7-step popup as designed:

![7-step popup](https://cloud.githubusercontent.com/assets/20033472/16746003/3bf33ebe-476d-11e6-9909-6a9f900f3b4b.png)

And here is a screenshot of the implementation (OSX 10.11.5 w/ Google Chrome):

<img width="332" alt="2016-07-11 13 36 12" src="https://cloud.githubusercontent.com/assets/20033472/16746017/51752734-476d-11e6-97b5-2f4cbba227b8.png">

Changes that need to be made include:

* Correct typography
* Correct the input box
* Remove the X (close window) button. User should be able to simple click outside of the popup to close it.
* Popup should be in a lightbox. e.g. (https://s3.amazonaws.com/shopify-app-store/2677def10128aaeda8361606e5a1bccb/screenshot/3889/original.jpg)
* Make sure graphics are at highest possible resolution without sacrificing speed.

**Comment by prakharbhatia** [comment]
Made a few changes on it. It looks better. Still under observation.

**Comment by prakharbhatia** [comment]
made the same design, tested it on Chrome, Firefox and Safari. Works good. Still under observation.

**Comment by prakharbhatia** [comment]
Fixed it few days ago, it was under observation due to caching. It looks good now.

**Comment by windupmicheal** [comment]
Can we center the text, "Email / Username" within the text box?

![2016-07-21 12 40 30](https://cloud.githubusercontent.com/assets/20033472/17036243/55716f3e-4f40-11e6-8791-44d8e827cffd.png)

**Comment by windupmicheal** [comment]
@highwayjourney We need to replace "Email / Username" with just "Email" and center it in the text box.

**Comment by highwayjourney** [comment]
Can you guide me get to this popup?

**Comment by windupmicheal** [comment]
Yep, we can skype

**Comment by highwayjourney** [comment]
Modified as requested.

**Comment by windupmicheal** [comment]
Fixed.
