### ISSUE TITLE
Need to fix video on homepage!

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#11]
Video on homepage is huge. See screenshot:

<img width="1368" alt="2016-07-12 16 18 01" src="https://cloud.githubusercontent.com/assets/20033472/16786799/57ad7f22-484c-11e6-9893-476f5e5f4424.png">

Needs to be set back to size relative to design brief.  See screenshot from design brief:

<img width="1233" alt="2016-07-12 16 19 39" src="https://cloud.githubusercontent.com/assets/20033472/16786811/783ee992-484c-11e6-95e6-eb43e388ee49.png">

**Comment by prakharbhatia** [comment]
This was browser issue and does not needs fixing !

**Comment by windupmicheal** [comment]
Verified, this was something weird happening in my browser.
