### ISSUE TITLE
Newsletter should be moved from Learning Center menu to Tools menu

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#12]
The "Newsletter" section should be moved from the Learning center menu to the Tools menu.

<img width="676" alt="2016-07-12 16 28 09" src="https://cloud.githubusercontent.com/assets/20033472/16787004/c49e5628-484d-11e6-8aac-6b69808fd2c3.png">

**Comment by prakharbhatia** [comment]
This is done, Newsletter is now in tools menu, removed it from Learning center menu
