### ISSUE TITLE
Fonts that are not bold on reports pages are gotham-htf, should be open sans

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#13]
The bold fonts on the reports pages (options, commodities, stock, and forex) are gotham-htf.

ALL CONTENT FONTS should be open sans.

**Comment by prakharbhatia** [comment]
Removed Gotham font from the site, now it would be all "Open Sans"

**Comment by prakharbhatia** [comment]
Issue kept under observation due to caching. Let me check the issue for few hours before closing it.

**Comment by prakharbhatia** [comment]
Open Sans all over.

**Comment by windupmicheal** [comment]
Looks good!
