### ISSUE TITLE
The title images next to reports articles do not need to be links

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#14]
The images for Forex Report, Options Report, Stock Report, and Commodities Report that floats to the left of the title paragraph is currently clickable, yet does nothing when clicked. These images do not need to be links. Please remove anchor tag.

**Comment by prakharbhatia** [comment]
This is fixed, now all 4 reports (options, forex, stock, commodity) top left  report logo images are not a link.
