### ISSUE TITLE
Contact Us form from site inconsistently doesn't deliver messages to team@tackletrading.com

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#15]
##When just asking a question, not as big a deal, but when it's someone wanting to cancel their subscription, that's a problem. Have had a few instances of it over the past few months, but whenever tested, the test emails always come through right away.

Issue came up again with a member needing to cancel their subscription yesterday, stating he tried a month ago to cancel through our contact us form, then three days ago, then he emailed us directly when he got no response.

Emails from most recent case follow:

"I would like to cancel my membership. I had sent two (2) previous messages on your site requesting membership cancellation (once in June, and the other yesterday, 14 July 16) and had never received any response back. I would also request that my credit card charge be reversed for the charge of July, since I had sent the previous request for cancellation."

"I sent the request through the website, not through email. I never received a response from it....Just finding an email address for Tackle Trading required that I do some digging, since it wasn't on the 'Contact Us' page."

**Comment by prakharbhatia** [comment]
I checked contact form and tried to send test email from both of them, they all were delivered fine. 
Probably the issue is at the user end.

I would suggest to add email address on the contact page, so that if someone faces similar issue, he could directly reach you on the email address.

**Comment by prakharbhatia** [comment]
Please suggest the next course of action

**Comment by windupmicheal** [comment]
Setting this to low priority. Will keep bug open for now and on the list of things to address in the future.

**Comment by windupmicheal** [comment]
@highwayjourney This has been a thorn in our sides. Can you investigate the contact form and see if you can track this issue down?

**Comment by windupmicheal** [comment]
Unless this becomes an urgent UX issue, I'm deferring this issue to the new website.
