### ISSUE TITLE
HIGH SEVERITY: List of content access is incorrect for every level on the 'learn more' page

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#16]
List of content access is incorrect for every level on the 'learn more' page. Also, every list both lists the coaches show twice and misspells it as 'coach's show'
What it should be:
Rookie:
- Tackle Trading Videos
- Forums and Podcast
-Trading Room Access

Varsity:
- Tackle Trading Videos
- Forums and Podcast
-Trading Room Access
-Weekly Newsletter
-Cash Flow Club

Pro
Everything

**Comment by prakharbhatia** [comment]
This is fixed !
