### ISSUE TITLE
Market Recap needs to be removed from the 'Free Videos' subcategory

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#17]
This is causing the actual videos that we do have to be buried under all the market recaps we're doing. Low severity.

**Comment by philtackletrading** [comment]
Starting to get complaints again about Video Vault being clogged up with market recaps and not having videos available unless you know what you're searching for.

**Comment by NoahTackleTrading** [comment]
We need to create a protocol for a searchable video database.  Who knows anything about this?

**Comment by philtackletrading** [comment]
It's one of my basecamp items to help get this organized based on video content.

**Comment by GinoPoore** [comment]
I got prakhar on it.

Should be fixed soon

gino

**Comment by windupmicheal** [comment]
@philtackletrading Is this still an issue?

**Comment by philtackletrading** [comment]
Closed and resolved.
