### ISSUE TITLE
Tackle Trading logo on homepage is too small

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#2]
Tackle Trading logo on upper-right corner of homepage is too small. Resolution is also a little low. Would like to increase size of logo and make it higher resolution.

<img width="985" alt="2016-06-28 18 15 42" src="https://cloud.githubusercontent.com/assets/20033472/16437499/61e781d6-3d5c-11e6-92e7-1f19d58817a7.png">

**Comment by windupmicheal** [comment]
fhsdfhsdfhsdfhsdfghdslkjfgh

**Comment by prakharbhatia** [comment]
please provide the exact dimensions in pixels. I would change it.

**Comment by prakharbhatia** [comment]
Please provide the size of the logo, so that I could make it bigger.

**Comment by windupmicheal** [comment]
Thanks, Prakhar! Would you please double the size that it is now and arrange it with the main menu so that it looks like this:

![2016-07-21 12 16 00](https://cloud.githubusercontent.com/assets/20033472/17036020/425fa6aa-4f3f-11e6-9f95-575dc6a45ec7.png)

**Comment by highwayjourney** [comment]
changed

**Comment by windupmicheal** [comment]
See if this works:

![modified logo with layers](https://cloud.githubusercontent.com/assets/20033472/18233567/83ff349e-729f-11e6-80dd-caefbb652b5c.png)

**Comment by highwayjourney** [comment]
changed with high-res logo

**Comment by windupmicheal** [comment]
Looks much better!
