### ISSUE TITLE
Users have to contact us directly to reset their password

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#20]
Other sites have an automated process that sends a 'password reset' email to the user. You have to contact Phil directly to get your password changed, which isn't secure.

**Comment by windupmicheal** [comment]
I will design a flow for this an assign to Leo

**Comment by highwayjourney** [comment]
Can we discuss the flow?

**Comment by windupmicheal** [comment]
I haven't designed anything for this yet. Leave this assigned to me for now. When I get something designed I'll bring you and Noah on board.

**Comment by windupmicheal** [comment]
Added in a "Forgot Password" link to login popup which sends an email to team@tackle.

Will consider making this more automated in the new website.
