### ISSUE TITLE
Rookie and Varsity purchase pages have wrong url and are mis-named on pages themselves

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#21]

**Comment by windupmicheal** [comment]
Please provide steps to repro so I know exactly what page you're talking about.

**Comment by philtackletrading** [comment]
The Visitor and Rookie levels were recently renamed to Rookie for Visitor, and Varsity for Rookie.

![rookievarsity1](https://cloud.githubusercontent.com/assets/20495058/18156241/166ab64e-6fd2-11e6-8a0f-67ae0995244f.jpg)


Clicking on Rookie still has the url and description on the page as 'Join Visitor'.

![rookievarsity3](https://cloud.githubusercontent.com/assets/20495058/18156235/0b505aca-6fd2-11e6-8e2a-4e7e0283a0b8.jpg)

Clicking on Varsity still has the url and description on the page as 'Join Rookie'.

![rookievarsity2](https://cloud.githubusercontent.com/assets/20495058/18156239/1153db18-6fd2-11e6-9216-7d490096ff56.jpg)

**Comment by windupmicheal** [comment]
Great catch. I think I can fix this one myself..

**Comment by windupmicheal** [comment]
Ok I fixed this, but I need Leo to change the ITEM in the purchase row from "Rookie monthly membership" to "varsity". Will close this and file a separate bug for that.
