### ISSUE TITLE
Remove author automatically appearing on posts

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#22]

**Comment by windupmicheal** [comment]
As with the dates bug, Please indicate steps to repro and include a screenshot of where exactly you're talking about. Just from articles/blogs? What about reports? etc.

Also wondering why we want to remove author names? I think it's potentially important to allow members to build a rapport with report authors..

**Comment by philtackletrading** [comment]
Pics will be EOB Monday. The author generates automatically when a post is done, which is a problem for when I'm the one posting for people doing guest spots for us. The author info would instead be its own section within the post itself to maintain that building of rapport that you mention. Right now, that isn't properly happening for anything I post for other people.

**Comment by philtackletrading** [comment]
![dateremoval](https://cloud.githubusercontent.com/assets/20495058/18064384/682d16f8-6dec-11e6-9b0e-04c50af4117d.jpg)Here's a pic sample of what should be removed.

**Comment by philtackletrading** [comment]
![name removal1](https://cloud.githubusercontent.com/assets/20495058/18064402/80be1abe-6dec-11e6-9c0e-e7a0a9cf1af1.jpg)
![name removal2](https://cloud.githubusercontent.com/assets/20495058/18064403/80c55180-6dec-11e6-9c73-0570f441deed.jpg)Here are the two locations the author should be removed (blue arrows). The yellow arrow in pic two shows what we would use for author info in every post instead.

**Comment by windupmicheal** [comment]
Assigning to Leo and setting priority to medium.

**Comment by highwayjourney** [comment]
removed the relevant parts

**Comment by windupmicheal** [comment]
@philtackletrading Can you verify that this is fixed on http://tackletrade.staging.wpengine.com/

Once we've verified that it's fixed on the staging site, we'll move it to the live site.

**Comment by windupmicheal** [comment]
Fix verified on http://tackletrade.staging.wpengine.com/

Closing bug.
