### ISSUE TITLE
Some users getting bounced back to front page from Cash Flow Club only

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#24]
Users in question are Pro members and can access rest of site fine. Bounce only happens with Cash Flow Club posts.

**Comment by windupmicheal** [comment]
@philtackletrading Would you please indicate steps to reproduce and user configuration requirements for reproduction (e.g. pro member? Rookie? logged in? not logged in? etc.)

**Comment by philtackletrading** [comment]
I can't beyond Pro Member and logged in, unfortunately.

**Comment by windupmicheal** [comment]
Do we need to create a "test user" for fixing and testing this scenario then? I'm still not 100% sure what problem is..

**Comment by philtackletrading** [comment]
...I've been thinking about this one specifically and it hasn't happened since. I'm closing it for now.
