### ISSUE TITLE
Change category for Market Scoreboard from 'Newsletter' to Market Scoreboard & tie it to Market Scoreboard main menu dropdown

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#25]

**Comment by windupmicheal** [comment]
I'm honestly not even sure what this is about. Please give more detail when entering issues.

**Comment by philtackletrading** [comment]
Made title more clear. There was no Market Scoreboard category when writing a post. They've been tagged as Newsletter.

![marketscoreboardcategory1](https://cloud.githubusercontent.com/assets/20495058/18156099/d395fca8-6fd0-11e6-9f04-40df01ccf487.jpg)


I've created a Market Scoreboard category now, but it's not tied to a specific main menu dropdown; the Market Scoreboard in the main menu dropdown is tied to Newsletter.

![marketscoreboardcategory2](https://cloud.githubusercontent.com/assets/20495058/18156104/d8e6cff2-6fd0-11e6-9c6e-7c23a1a1c884.jpg)

![marketscoreboardcategory3](https://cloud.githubusercontent.com/assets/20495058/18156107/e185c5c8-6fd0-11e6-8f25-dfff52584f5c.jpg)

That needs to be fixed by making the Market Scoreboard in the dropdown menus be tied to the Market Scoreboard category.

**Comment by windupmicheal** [comment]
Good catch. Fixed.
