### ISSUE TITLE
Formatting of forums table columns is way off

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#28]
I'm using a standard 15" macbook pro, maximized Chrome browser. See screenshot:

<img width="1239" alt="2016-08-29 16 59 56" src="https://cloud.githubusercontent.com/assets/20033472/18071454/ba2785e2-6e0a-11e6-85b9-c9972ac77c91.png">

**Comment by highwayjourney** [comment]
resolved the layout issue. It uses different layout for column captions and data fields. And there are old files that disturbing me. I guess we will need some cleaning on code structure removing unused codes or duplicated codes, restructuring , however, we'd better do some time later when I'm much more familiar with the structure.

**Comment by windupmicheal** [comment]
Verified. Looks fixed on http://tackletrade.staging.wpengine.com/forums/

Can be pushed to live server.
