### ISSUE TITLE
Main drop-down menu disappears over "Recent Posts" carousel

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#29]
The main menu disappears when you try to click on something that extends into the "Recent Posts" slider carousel.

Steps to repro:
1) Go to tackletrading.com
2) Mouse over Home, click on Recent Posts
3) Notice Recent Posts page has loaded
4) Mouse over Club House
5) Move the mouse down the Club House menu and try to click on Podcasts or Coaches Show or anything below that.

Results:
If the menu item is extended over the top of the "recent posts" slider carousel, the main menu dropdown disappears when you mouse over lower parts of it.

<img width="1432" alt="2016-08-30 10 10 49" src="https://cloud.githubusercontent.com/assets/20033472/18099330/d35d1b04-6e9a-11e6-844f-63047d42f966.png">

**Comment by windupmicheal** [comment]
System setup: 15" macbook pro with latest Chrome browser

**Comment by highwayjourney** [comment]
I'm on El Capitan with latest Chrome browser. And I can't reproduce it or pin it. Please advise.

**Comment by windupmicheal** [comment]
I'm using the same config. I can do a screenshare and show you. I'm on Slack now, let me know when you're around.

**Comment by windupmicheal** [comment]
We met on skype and I showed you how to repro this. Are you good on this for now or do you need further assistance?

**Comment by highwayjourney** [comment]
That description was enough. I will fix it soon.

**Comment by windupmicheal** [comment]
Unless this becomes an urgent UX issue, I'm deferring this to the new website.
