### ISSUE TITLE
Too many spaces between SIGN OUT  |  MY ACCOUNT

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#3]
There appears to be two spaces between SIGN OUT and the pipe character "|". Also two spaces between the pipe character "|" and MY ACCOUNT.

This is also true of the LOGIN  |   SIGNUP state.

Furthermore, the HREF link for LOGIN and SIGN OUT seems to extend to the spacing after the text. See screenshots:

<img width="202" alt="2016-06-28 18 44 17" src="https://cloud.githubusercontent.com/assets/20033472/16438006/9b043938-3d60-11e6-8147-d90c498c8d39.png">
<img width="140" alt="2016-06-28 18 45 21" src="https://cloud.githubusercontent.com/assets/20033472/16438007/9b04dd20-3d60-11e6-942d-aacb311ee686.png">

**Comment by prakharbhatia** [comment]
Working on it. Would provide an update soon.

**Comment by highwayjourney** [comment]
Current styling of this part is bad. It uses different styling for left item and right item. For example, it uses space character for left spacing and margin for right spacing. It will need some careful modification.

**Comment by highwayjourney** [comment]
styling is fixed and I removed some complex codes and duplicated codes.

**Comment by windupmicheal** [comment]
Fixed.
