### ISSUE TITLE
Main drop down menus disappear when using search box

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#30]

**Comment by windupmicheal** [comment]
@philtackletrading I can type in the Search bar and mouse over the main menus just fine with Chrome on my macbook. Can you include a better description of the problem and steps to reproduce, please?

**Comment by philtackletrading** [comment]
Windows 10, Chrome.

1. Type anything into search box and click 'search'.
2. Following window has no navigation menus.

![no nav bar](https://cloud.githubusercontent.com/assets/20495058/18155809/5a5e5bd4-6fce-11e6-8fe8-68473bcda41f.jpg)

**Comment by windupmicheal** [comment]
WOW, that's not good. Changing to high severity and assigning to Leo.

**Comment by highwayjourney** [comment]
fixed it and now it shows dropdown menu.

**Comment by windupmicheal** [comment]
Verified fix on staging site. Closing bug. Can be pushed to live site.
