### ISSUE TITLE
"Join Varsity" page lists "rookie membership" as item being purchased

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#31]
Item being purchased should be listed as "Varsity Monthly Membership", not rookie.

<img width="1224" alt="2016-09-02 20 02 37" src="https://cloud.githubusercontent.com/assets/20033472/18222306/6cb3cf8c-7148-11e6-9a8f-9de79da797cc.png">

**Comment by highwayjourney** [comment]
I need some more description on this. Maybe we can use Slack channel.

**Comment by windupmicheal** [comment]
Fixed on Ontraport with help from Phil and Neil.
