### ISSUE TITLE
Rookie "FREE" link is pointed at the wrong page

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#32]
Rookie "FREE" link on the Learn More page is points to https://www.tackletrading.com/join-visitor/, but it should point to http://tackletrading.com/join-rookie/

<img width="599" alt="2016-09-02 20 07 14" src="https://cloud.githubusercontent.com/assets/20033472/18222323/1febd950-7149-11e6-854e-171795fba8c5.png">

**Comment by highwayjourney** [comment]
modified the URL link. I had to do some restructuring of codes.
By the way, free membership button and $27 button points same link "join-rookie". 
Is this right?

**Comment by windupmicheal** [comment]
They are separate bugs. Looks like this one is fixed. I'll follow up with the others..
