### ISSUE TITLE
http://tackletrading.com/join-rookie/ forwards to http://tackletrading.com/join-varsity/

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#33]
If you try to go to http://tackletrading.com/join-rookie/ you get automatically forwarded to http://tackletrading.com/join-varsity/

Since the "FREE" link to "Join Rookie" from the learn more page isn't functioning right now, you have to just type the URL into your browser, but once we get that "FREE" link fixed, this bug will become more apparent.

**Comment by highwayjourney** [comment]
resolved.

**Comment by windupmicheal** [comment]
Fix verified on staging site.
