### ISSUE TITLE
Testimonials formatting needs to be completely fixed

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#34]
The formatting of the testimonials on the "Learn More" page is a disaster... http://tackletrading.com/learn-more/

See screenshots:

<img width="731" alt="2016-09-04 13 05 41" src="https://cloud.githubusercontent.com/assets/20033472/18233596/79586348-72a0-11e6-9c7b-ac4d9706c9b6.png">
<img width="1431" alt="2016-09-04 13 05 50" src="https://cloud.githubusercontent.com/assets/20033472/18233597/7958b474-72a0-11e6-80a6-a2f23d34bf90.png">
<img width="1429" alt="2016-09-04 13 06 02" src="https://cloud.githubusercontent.com/assets/20033472/18233595/795554c8-72a0-11e6-8556-73e9e6c79113.png">

Testimonials should be formatted to look like this:

![membership sales page](https://cloud.githubusercontent.com/assets/20033472/18233602/915d1560-72a0-11e6-8db6-12037be5c8ae.png)

**Comment by highwayjourney** [comment]
It is updated and it's now working properly.

**Comment by windupmicheal** [comment]
Perhaps due to rolling back the website, the testimonials section formatting is broken once again. See screenshot:

<img width="1435" alt="screen shot 2016-10-06 at 12 27 39" src="https://cloud.githubusercontent.com/assets/20033472/19167396/5a50a2f6-8bc0-11e6-9f62-3fdc1f18e4e7.png">

**Comment by windupmicheal** [comment]
This appears to be mostly fixed, with a slight visual error on transitions. Good enough for rock n roll, deferring further work on this to the new site.
