### ISSUE TITLE
Visual error in join-rookie sign-up page

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#37]
There are visual errors in the sign-up form for the join-rookie page at https://tackletrading.com/join-rookie/

See screenshot:

<img width="620" alt="2016-09-06 13 27 29" src="https://cloud.githubusercontent.com/assets/20033472/18289819/def1e27e-7435-11e6-800f-737a764b74a7.png">

**Comment by highwayjourney** [comment]
Email inputbox is in right place now, anyway, alert circle icon needs some complicated modification, so we'd better leave it and wait for next update.

**Comment by windupmicheal** [comment]
Verified that the email inputbox is fixed. Will keep this bug open until the alert icon is fixed.

**Comment by windupmicheal** [comment]
This bug still exists in all its entirety.

**Comment by windupmicheal** [comment]
Fixed.
