### ISSUE TITLE
Text at top of Learn More page is difficult to read

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#38]
Need to make this text more readable, perhaps with a semi-transparent background. http://tackletrading.com/learn-more/

<img width="642" alt="2016-09-06 13 33 41" src="https://cloud.githubusercontent.com/assets/20033472/18290031/af7a0e8a-7436-11e6-8351-2134e84a5ba1.png">

**Comment by highwayjourney** [comment]
placed semi-transparent background.

**Comment by windupmicheal** [comment]
Keep trying. I don't like this solution, it's still hard to read. Clarity should be top priority. Try increasing opacity, maybe? If you have other design ideas, I'm open. This is a temporary solution so it doesn't have to be perfect.

**Comment by highwayjourney** [comment]
I've increased the opacity. We can try with other font colors and background colors if you don't like current solution.

**Comment by windupmicheal** [comment]
waaaay better. Closing this bug.

**Comment by windupmicheal** [comment]
Issue returned after fixing pilot press bug

**Comment by windupmicheal** [comment]
Fixed.
