### ISSUE TITLE
Reported issues logging in and accessing paid content through iPhone 6

### ISSUE THREAD

**Issue by philtackletrading** [windupmicheal/Tackle-Trading#41]
From the customer directly when trying to access Coaches Show Replay link through mobile via iPhone 6:

"[When clicking on the Coaches Show Replay link from email], it generally takes me to the home page, but won't let me access the specific reports from there or even log in -- if I am on mobile."

Don't have steps to repro as I'm an Android user.

**Comment by windupmicheal** [comment]
Our mobile site is a total disaster and we know it. It's on the docket of things to work on, but we're pressed for resources and time. @philtackletrading , keep in touch with me and let me know how much users are complaining about this. Their complaints will drive the priority.
