### ISSUE TITLE
Add Events Calendar Plugin

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#44]
Leo,

This is part bug, but part enhancement request. As we discussed in Slack, I want to remove the current "weekly schedule" that we have and add in the Wordpress "Events Calendar" plugin.

<img width="1134" alt="2016-09-27 10 09 35" src="https://cloud.githubusercontent.com/assets/20033472/18884215/4d5af974-849b-11e6-89b9-aba4c78160ab.png">

First, let's make this page go to the Events Calendar plugin.

Let me know when you get the calendar plugin installed and I'll setup the events.

**Comment by highwayjourney** [comment]
We should do that after resolving PP issue. After that, I will add events calendar plugin and let you know.

**Comment by windupmicheal** [comment]
Great job, Leo, thank you! Closing this.
