### ISSUE TITLE
Implement new 404 page

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#45]
Implement this 404 page in replace of the current one.

Here is a PDF with the design:

[404.pdf](https://github.com/windupmicheal/Tackle-Trading/files/499843/404.pdf)

And here is a link to some animation on Codepen that I would like to implement: https://codepen.io/mrwindupbird/full/BLkXwg/

**Comment by highwayjourney** [comment]
implemented on live server (without the input controls)

**Comment by windupmicheal** [comment]
Looks good, Leo! Changing priority to low but keeping this issue open until the input controls are implemented.

**Comment by windupmicheal** [comment]
Deferring further development on this to the new site.
