### ISSUE TITLE
Footer menu formatting error

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#47]
Learning Center should be in its own column:

<img width="711" alt="screen shot 2016-10-08 at 12 07 45" src="https://cloud.githubusercontent.com/assets/20033472/19215334/e7cfad12-8d4f-11e6-94be-9681b3c1d888.png">

**Comment by highwayjourney** [comment]
styling on conditions related to width given so that 5 menu blocks show properly.

**Comment by windupmicheal** [comment]
Fixed.
