### ISSUE TITLE
New header design + modification to stylesheet

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#48]
Notice:
- The new all-white logo
- New menu font
- The location of LOGIN | SIGNUP so that the P in SIGNUP is virtically aligned with the magnifying glass of the search bar
- New Login/signup/logout font
- New "Active Menu" locator - the grey highlight oval surrounding the currently expanded menu
- The font and light-grey color of the SEARCH text 
- The location of the magnifying glass in the SEARCH bar

You'll notice that the menu headers are using the "MUSEO SLAB" font, which is available from typekit.com. I have Noah's credentials for this. Ask me for them in private when you are ready.

According to a wpengine.com scan, we're using FIVE fonts on the site. That is two too many. I would like to adjust the stylesheet to use MUSEO SLAB font for all headers, and HELVETICA NEUE for paragraph text. The only other font that should be used is AERO, which is the logo font and the font for headers on the LEARN MORE page. No other fonts should be used on the site. Where OPEN SANS is used in the footer, let's use HELVETICA NEUE.

You should be able to pull graphic assets from this PDF file. If not, let me know what you need and I'll get it to you.

[new front page w video bg.pdf](https://github.com/windupmicheal/Tackle-Trading/files/546130/new.front.page.w.video.bg.pdf)

**Comment by GinoPoore** [comment]
Like it all except the logo being all white,

That being red and black will stand out with the greyscale background.

g..

**Comment by windupmicheal** [comment]
@GinoPoore I don't care for the white logo, either. Noah outranked me on that design call.

The black in the current logo gets lost too much in the video background, so ~something~ had to be done.

I did do a version of the logo with white and red that I believe works well:

<img width="759" alt="screen shot 2016-10-25 at 11 21 17" src="https://cloud.githubusercontent.com/assets/20033472/19698687/2d215a3e-9aa5-11e6-930f-30f7a5192828.png">

@NoahTackleTrading we may have another vote for white and red. You guys should discuss it and get back to me.

@highwayjourney Please continue implementing the white logo for now, we can change it out later if need be.

**Comment by windupmicheal** [comment]
I can also try a version with a "light grey" and red logo that wouldn't POP as loudly as the white and red logo does.. Let me know if you want me to try that.

**Comment by GinoPoore** [comment]
Is there a animated like changing color logo,  

Like something that highlights the logo or traces it with a border color?

**Comment by GinoPoore** [comment]
White and red stand out better than just white or black and red

**Comment by windupmicheal** [comment]
I don't think animating the logo is a great idea. That breaks all sorts of basic identity/branding rules, which I don't think we should do without good reason.

I tried doing a white "outer glow" for the original logo to improve visibility, but did not like the way it turned out:

<img width="759" alt="screen shot 2016-10-25 at 15 11 29" src="https://cloud.githubusercontent.com/assets/20033472/19706172/576a196e-9ac5-11e6-9805-d58f0cd64040.png">

**Comment by windupmicheal** [comment]
Here's a mockup of a light grey and red logo:

<img width="766" alt="screen shot 2016-10-25 at 15 37 34" src="https://cloud.githubusercontent.com/assets/20033472/19706853/03be78ba-9ac9-11e6-9c35-5c32aed531de.png">

**Comment by highwayjourney** [comment]
@windupmicheal I'm still keeping white logo. Please let me know if you all get to decision.

**Comment by windupmicheal** [comment]
Great work, Leo! Closing this.
