### ISSUE TITLE
"Membership Content Only" page for implementation

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#49]
Here is the "Membership Content Only" page for implementation.

[members-only content.pdf](https://github.com/windupmicheal/Tackle-Trading/files/546148/members-only.content.pdf)

**Comment by windupmicheal** [comment]
To be clear, this page that should popup whenever a browser attempts to access content that is restricted beyond their membership level.

Some examples:

- If a non-registered/not-logged-in user attempts to access the Clubhouse, this page should pop up.
- If a Rookie member attempts to access the Cash Flow Club, this page should pop up.
- If a Varsity member attempts to access the Scouting Reports, this page should pop up.

**Comment by highwayjourney** [comment]
Implemented.

**Comment by windupmicheal** [comment]
Looks good!
