### ISSUE TITLE
The three forum sections should be on one single page.

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#5]
There are currently three forum sections under clubhouse: Trading Forums, Legacy Courses, and Scouting Reports.

All forums should be organized on one single page, as layed out in the forum design brief. The top level forum page should be labeled simply, "Trading Forums" and should be located under the Club House menu.

<img width="219" alt="2016-06-28 19 07 37" src="https://cloud.githubusercontent.com/assets/20033472/16438348/d12120be-3d63-11e6-82e3-2ff71a53dea6.png">

**Comment by windupmicheal** [comment]
Looks like all three forum sections are available on the Trading Forums page now, but the Legacy Courses and Scouting Reports menu items still exist. These menu items need to be deleted.

<img width="225" alt="2016-07-11 13 32 08" src="https://cloud.githubusercontent.com/assets/20033472/16745783/58aadebe-476c-11e6-92cd-633cd603b464.png">

**Comment by prakharbhatia** [comment]
Fixed it. Now there is only one Link for forums under club house. ie "Trading Forums"

**Comment by windupmicheal** [comment]
Perfect!
