### ISSUE TITLE
"Page loading" animation

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#52]
This is an enhancement request, not a bug.

With the Tackle site growing both in size and complexity, and especially with a video loading on the front page now, I think it might be efficacious for us to have a "page loading" animation.

I like this: http://codepen.io/craij/full/LENzgm/

But perhaps we could make it smaller and remove the "loading" text, similar to the designtaxi website. Example: http://designtaxi.com/news/389385/Microsoft-Surface-Studio-A-Powerful-Workstation-Designed-For-Creatives/  (click "skip the ad" and you'll see the animation as the target page loads)

Leo, any thoughts on this? I don't want to create bloat, but I would like to include little things that make the site more "delightful". Let me know..

**Comment by highwayjourney** [comment]
@windupmicheal I think that's a good idea.
The loading animation looks OK but too complex, so maybe we can make it simple like designtaxi animation.

**Comment by windupmicheal** [comment]
Since it's mostly CSS with just 5 lines of JS, I was under the impression that it would run quickly despite its complexity.

But yeah, we can certainly simplify.

**Comment by windupmicheal** [comment]
Deferring to new site
