### ISSUE TITLE
All instances of time in events calendar should have "ET" suffix to indicate Eastern Time

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#58]
<img width="412" alt="2016-11-02 9 40 58" src="https://cloud.githubusercontent.com/assets/20033472/19938021/afcf8212-a0e0-11e6-8741-32b3db45e9bd.png">
<img width="1091" alt="2016-11-02 9 41 15" src="https://cloud.githubusercontent.com/assets/20033472/19938020/afcc4cbe-a0e0-11e6-93bd-180c55d73a2b.png">

**Comment by highwayjourney** [comment]
please check.

**Comment by windupmicheal** [comment]
Still not showing time zone delineation here:

<img width="378" alt="2016-11-02 11 28 23" src="https://cloud.githubusercontent.com/assets/20033472/19942015/83ad11b8-a0ef-11e6-8533-e849bd18c0e6.png">

**Comment by windupmicheal** [comment]
This final instance of the event time is not easily adjusted and is rather superfluous to boot. Closing.
