### ISSUE TITLE
Footer copyright and MWUB link text should be centered

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#6]
The three lines of text below the social media icons are currently left-justified, but should all be centered.

<img width="324" alt="2016-06-28 19 15 47" src="https://cloud.githubusercontent.com/assets/20033472/16438477/e6422014-3d64-11e6-8edf-fa07000f2616.png">

**Comment by prakharbhatia** [comment]
All three lines centered now.
