### ISSUE TITLE
Adjust width of Learning center dropdown menu

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#61]
Need to adjust the width of Learning Center dropdown menu so that "cash flow club" and "coaches show" do not wrap. It is probably ok if "Tales of a Technician" wraps since it's so long..

<img width="207" alt="screen shot 2016-11-04 at 9 26 01" src="https://cloud.githubusercontent.com/assets/20033472/20013582/efc20584-a270-11e6-98be-19e6b0340514.png">

**Comment by highwayjourney** [comment]
it's modified and now all menu items look ok.

**Comment by windupmicheal** [comment]
Great, thanks Leo!
