### ISSUE TITLE
Login popup is missing icons

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#62]
This is what the login popup currently looks like:

<img width="355" alt="screen shot 2016-11-06 at 15 21 26" src="https://cloud.githubusercontent.com/assets/20033472/20042790/dd949b86-a434-11e6-9e19-031fa043b0d9.png">

This is what it should look like:

![sign-in popup](https://cloud.githubusercontent.com/assets/20033472/20042791/e3ee678c-a434-11e6-8231-03a656f43af1.png)

**Comment by windupmicheal** [comment]
It seems the problem is somehow related to Chrome's autofill of username and pwd. Would still like to fix this when there is time.

**Comment by highwayjourney** [comment]
@windupmicheal Staging server involves revised login dialog. Please check.

**Comment by windupmicheal** [comment]
Fix verified on my laptop with Chrome and field autofill
