### ISSUE TITLE
Copyright footer text below social icons should be "open sans" font

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#7]
They are currently gotham HTF, they should be open sans. All content text on the site should be changed to open sans.

<img width="324" alt="2016-06-28 19 15 47" src="https://cloud.githubusercontent.com/assets/20033472/16438491/0d16a16a-3d65-11e6-8e0f-20d92aa0ba00.png">

**Comment by prakharbhatia** [comment]
Changed the font. Kept under observation due to caching.

**Comment by prakharbhatia** [comment]
It is all Open Sans now.
