### ISSUE TITLE
Mr. Wind-Up Bird link in footer should be underlined

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#8]
It should be clear that this is a link. The `<A>` tag should look something like this:

Website by `<A HREF="http://mrwindupbird.com>Mr. Wind-Up Bird Marketing & Design</A>`

The link part of the text, "Mr. Wind-Up Bird Marketing & Design", should be underlined.

**Comment by prakharbhatia** [comment]
The link is underlined now.
