### ISSUE TITLE
"Message" placeholder text needs an extra line break in message box on contact form

### ISSUE THREAD

**Issue by windupmicheal** [windupmicheal/Tackle-Trading#9]
In the contact form at the footer, the "Message" text is right up against the top of the input box. It needs to be moved down to match the visual scheme of the form.

<img width="375" alt="2016-06-28 19 32 52" src="https://cloud.githubusercontent.com/assets/20033472/16438806/86d268ca-3d67-11e6-8414-d3eac7654339.png">

**Comment by prakharbhatia** [comment]
Fixed. Now it has 5 pixels of padding from the top and it not touching the top border.
